[package]
name = "pyfoyer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyfoyer"
crate-type = ["cdylib"]

[dependencies]
bytes = "1.10.1"
foyer = "0.17.3"
pyo3 = "0.25.0"
