class CacheEntry:
    def key(self) -> bytes: ...
    def value(self) -> bytes: ...

class Cache:
    def __init__(self, capacity: int): ...
    def insert(self, key: bytes, value: bytes) -> CacheEntry: ...
    def contains(self, key: bytes) -> bool: ...
    def get(self, key: bytes) -> bytes | None: ...
    def remove(self, key: bytes) -> CacheEntry: ...
    def clear(self) -> None: ...
    def usage(self) -> int: ...
    def capacity(self) -> int: ...
    def shards(self) -> int: ...

class CacheBuilder:
    def __init__(self, capacity: int): ...
    def with_name(self, name: str) -> CacheBuilder: ...
    def with_shards(self, shards: int) -> CacheBuilder: ...
    def build(self) -> Cache: ...

class EvictionConfig:
    def fifo(self, cfg: FifoConfig) -> EvictionConfig: ...
    def s3fifo(self, cfg: S3FifoConfig) -> EvictionConfig: ...
    def lru(self, cfg: LruConfig) -> EvictionConfig: ...
    def lfu(self, cfg: LfuConfig) -> EvictionConfig: ...

class FifoConfig:
    def __init__(self): ...

class S3FifoConfig:
    def __init__(
        self,
        small_queue_capacity_ratio: float | None = None,
        ghost_queue_capacity_ratio: float | None = None,
        small_to_main_freq_threshold: int | None = None,
    ): ...
    @property
    def small_queue_capacity_ratio(self) -> float | None: ...
    @property
    def ghost_queue_capacity_ratio(self) -> float | None: ...
    @property
    def small_to_main_freq_threshold(self) -> int | None: ...

class LruConfig:
    def __init__(self, high_priority_pool_ratio: float | None = None): ...
    @property
    def high_priority_pool_ratio(self) -> float | None: ...

class LfuConfig:
    def __init__(
        self,
        window_capacity_ratio: float | None = None,
        protected_capacity_ratio: float | None = None,
        cmsketch_eps: float | None = None,
        cmsketch_confidence: float | None = None,
    ): ...
    @property
    def window_capacity_ratio(self) -> float | None: ...
    @property
    def protected_capacity_ratio(self) -> float | None: ...
    @property
    def cmsketch_eps(self) -> float | None: ...
    @property
    def cmsketch_confidence(self) -> float | None: ...
